##################################################################
# USERS - TESTE DE CRUD (C=CREATE(POST), R=LEITURA(GET), U=UPDATE, D=DELETE
# path of prodution - https://course-java-springboot-michael.herokuapp.com
##################################################################

####
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "Bob Brown",
  "email": "bob@gmail.com",
  "phone": "977557755",
  "password": "123456"
}


####

####
GET https://course-java-springboot-michael.herokuapp.com/users
####

####
GET http://localhost:8080/users/7
####

####
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "name": "Ana Carolina",
  "email": "ana@gmail.com",
  "phone": "977557788"

}

####
DELETE http://localhost:8080/users/3
####




##################################################################
# CATEGORY - TESTE DE CRUD (C=CREATE(POST), R=LEITURA(GET), U=UPDATE, D=DELETE
##################################################################

####
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Games"

}

####

####
GET http://localhost:8080/categories
####


####
GET http://localhost:8080/categories/1
####

####
PUT http://localhost:8080/categories/1
Content-Type: application/json

{
  "name": "Music"
}

####

####
DELETE http://localhost:8080/categories/3
####

##################################################################
# ORDER - TESTE DE CRUD (C=CREATE(POST), R=LEITURA(GET), U=UPDATE, D=DELETE
##################################################################

####
POST http://localhost:8080/orders
Content-Type: application/json

{
  "moment": "2019-06-20T19:53:07Z",
  "orderStatus": "PAID",
  "client": 2

}

####

####
GET http://localhost:8080/orders
####


####
GET http://localhost:8080/orders/1
####

##################################################################
# PRODUCT - TESTE DE CRUD (C=CREATE(POST), R=LEITURA(GET), U=UPDATE, D=DELETE
##################################################################

POST http://localhost:8080/products
Content-Type: application/json

{
  "moment": "2019-06-20T19:53:07Z",
  "orderStatus": "PAID",
  "client": 2

}

####
####
GET http://localhost:8080/products
####


####
GET http://localhost:8080/products/3
####